export const CHECK_AUTH                     = 'CHECK_AUTH'
export const CHECK_AUTH_START               = 'CHECK_AUTH_START'
export const CHECK_AUTH_SUCCESS             = 'CHECK_AUTH_SUCCESS'
export const CHECK_AUTH_FAIL                = 'CHECK_AUTH_FAIL'
export const CHECK_AUTO_LOGIN               = 'CHECK_AUTO_LOGIN'
export const LOG_OUT                        = 'LOG_OUT'

export const START_ACTION                   = 'START_ACTION'
export const LOAD_TICKETS                   = 'LOAD_TICKETS'
export const LOAD_TICKETS_FAILED            = 'LOAD_TICKETS_FAILED'
export const LOAD_TICKETS_SUCCESS           = 'LOAD_TICKETS_SUCCESS'
export const BROWSE_TICKET                  = 'BROWSE_TICKET'
export const BROWSE_TICKET_SUCCESS          = 'BROWSE_TICKET_SUCCESS'
export const BROWSE_TICKET_FAILED           = 'BROWSE_TICKET_FAILED'
export const CLEAR_CURRENT_SELECTED_TICKET  = 'CLEAR_CURRENT_SELECTED_TICKET'
export const CREATE_TICKET                  = 'CREATE_TICKET'
export const CREATE_TICKET_SUCCESS          = 'CREATE_TICKET_SUCCESS'
export const CREATE_TICKET_FAILED           = 'CREATE_TICKET_FAILED'